config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  post 'movie' => 'data_submission#update'
  post 'movies' => 'data_submission#new'
  get 'destroy_movie' => 'data_submission#destroy_movie'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
require 'faker'

class Movie < ApplicationRecord
  def self.active_movies
    Movie.all.where(:is_active => true).order('id desc')
  end

  def self.faker
    Movie.create(
             :name          => Faker::Name.unique.name,
             :release_year  => ((1950 + rand(65)).to_s + "0606").to_date,
             :rating        => rand(5),
             :is_active     => true
    ) rescue nil
  end

  def self.add(params)
    Movie.create(
        :name         => params['name'],
        :release_year => params['release_year'] ,
        :rating       => params['rating'],
        :is_active    => params['is_active']
    ) rescue nil
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/data_submission_controller.rb
class DataSubmissionController < ApplicationController
  def destroy_movie
    Movie.find(params['movie_id']).update(
                                      :is_active => false
    )
    redirect_back fallback_location: root_path
  end

  def update
    Movie.find(params['movie_id']).update(
        :name         => params['name'],
        :release_year => "#{params['year_name']}0606".to_date,
        :rating       => params['rating']
    )
    redirect_back fallback_location: root_path
  end

  def new
    Movie.add(
        params.merge(
            'is_active'    => true,
            'release_year' => "#{params['year_name']}0606".to_date
        )
    )
    redirect_back fallback_location: root_path
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @movies = Movie.active_movies
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/data_submission_helper.rb
module DataSubmissionHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-light bg-light">
  <a class="navbar-brand" href="<%= root_path  %>">
    <img src="https://getbootstrap.com/docs/4.0/assets/brand/bootstrap-solid.svg" width="30" height="30" class="d-inline-block align-top" alt="">
    Movies Manager
  </a>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app>
  <head>
    <title>MovieManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header'  %>
    <%= yield %>
  </body>
</html>

app/views/welcome/_movie_form.html.erb
<button type="button" class="btn btn-secondary btn-sm" data-toggle="modal" data-target="#movie_form_modal_<%= movie.id if movie.id %>" style="margin-bottom: 1%;">
  <%= button_text %>
</button>

<!-- Modal -->
<div class="modal fade" id="movie_form_modal_<%= movie.id if movie.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_with(model: movie, local: true, method: 'post') do |form| %>
          <%= form.hidden_field :movie_id, value: movie.id, name: 'movie_id' %>
          <div class="form-group">
            <%= form.label :name %>
            <%= form.text_field :name, class: "form-control", name: 'name' %>
          </div>


          <div class="form-group">
            <%= form.label :year %>
            <input type="text" list="years" class="form-control" name="year_name" value="<%= movie.release_year.cwyear if movie.release_year  %>" required>
          </div>

          <div class="form-group">
            <%= form.label :rating %>
            <select class="form-control" name="rating" required>
              <% for i in 1..5 %>
                <option value="<%= i %>" <%= 'selected' if movie.rating && movie.rating == i %>><%= i %></option>
              <% end %>
            </select>
          </div>

          <div class="actions">
            <%= form.submit button_text, class: 'btn btn-secondary btn-sm' %>
          </div>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>



<datalist id="years">
  <% for i in 1..118 %>
    <option value="<%= 1900 + i %>"></option>
  <% end %>
</datalist>

app/views/welcome/index.html.erb
<div class="container" style="padding-top: 1%;">
  <%= render 'welcome/movie_form', movie: Movie.new, button_text: 'Create Movie'  %>
  <table class="table table-bordered">
    <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Movie Name</th>
      <th scope="col">Year</th>
      <th scope="col">Rating</th>
      <th scope="col">Settings</th>
    </tr>
    </thead>
    <tbody>
    <% @movies.each_with_index do |movie,idx| %>
      <tr>
        <th scope="row"><%= idx + 1  %></th>
        <td><%= movie.name  %></td>
        <td><%= movie.release_year.cwyear  %></td>
        <td><%= movie.rating  %></td>
        <td>
          <%= render 'welcome/movie_form', movie: movie, button_text: 'Update Movie'  %>
          <%= link_to 'Destroy Movie', destroy_movie_path(:movie_id => movie.id), class: "btn btn-danger btn-sm", style: "margin-bottom: 1%;color:white;", method: :get, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>